output "env_config" {
  description = "Environment variables for .env file"
  value       = <<-EOT
# Azure OpenAI (generated by tofu)
AZURE_OPENAI_API_KEY=${azurerm_cognitive_account.openai.primary_access_key}
AZURE_OPENAI_ENDPOINT=${azurerm_cognitive_account.openai.endpoint}
AZURE_OPENAI_API_VERSION=2024-04-01-preview
EOT
  sensitive = true
}
